# Generated by Django 5.1.3 on 2024-12-07 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='daly_visit',
            field=models.IntegerField(default=1, verbose_name='Количество ежедневных входов'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='key_free_case',
            field=models.IntegerField(default=0, verbose_name='Количество ключей "Бесплатный кейс"'),
        ),
        migrations.AddField(
            model_name='user',
            name='key_wheel_of_fortune',
            field=models.IntegerField(default=0, verbose_name='Количество ключей "Колесо фортуны"'),
        ),
        migrations.AddField(
            model_name='user',
            name='tg_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='utm_label',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Casino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('free_spin', models.IntegerField(blank=True, null=True)),
                ('dep', models.IntegerField(blank=True, null=True, verbose_name='Процент к депозиту')),
                ('money', models.IntegerField(blank=True, null=True, verbose_name='+ Деньги при пополнении баланса')),
                ('url', models.URLField()),
                ('bonus', models.TextField(blank=True, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casino', to='kazik.image')),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('promo_code', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='количество призов (ключи,деньги)')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prize', to='kazik.image')),
            ],
        ),
        migrations.CreateModel(
            name='My_Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_bag', to='kazik.user')),
                ('prizes', models.ManyToManyField(blank=True, null=True, related_name='my_bag', to='kazik.prize')),
            ],
        ),
        migrations.CreateModel(
            name='Daly_Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=1)),
                ('prizes', models.ManyToManyField(related_name='daly_bonus', to='kazik.prize')),
            ],
        ),
    ]
