# Generated by Django 5.1.3 on 2024-12-09 13:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazik', '0003_rename_name_user_tg_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casino',
            old_name='bonus',
            new_name='promo_code',
        ),
        migrations.AddField(
            model_name='casino',
            name='count_of_visit_people',
            field=models.IntegerField(default=0, verbose_name='Количество переходов в казино '),
        ),
        migrations.AddField(
            model_name='casino',
            name='number_of_casino',
            field=models.IntegerField(default=0, verbose_name='Порядок (нумерация) для фильтров'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_get_daly_bonus',
            field=models.BooleanField(default=True, verbose_name='можно ли получить бонус'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_visit',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата последнего захода в мини апп '),
        ),
        migrations.CreateModel(
            name='Personal_Visit_on_Casino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_of_visit', models.IntegerField(default=0, verbose_name='Количество переходов ')),
                ('casino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_visit_on_casino', to='kazik.casino')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_visit_on_casino', to='kazik.user')),
            ],
        ),
    ]
