# Generated by Django 5.1.3 on 2024-12-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazik', '0004_rename_bonus_casino_promo_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_visit',
            field=models.DateField(auto_now_add=True, verbose_name='Дата последнего захода в мини апп '),
        ),
    ]
