# Generated by Django 5.1.3 on 2024-12-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazik', '0005_alter_user_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casino',
            name='number_of_casino',
            field=models.IntegerField(verbose_name='Порядок (нумерация) для фильтров'),
        ),
    ]
