# Generated by Django 5.1.3 on 2024-12-09 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazik', '0007_alter_casino_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='daner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casino_baner', to='kazik.image'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casino_logo', to='kazik.image'),
        ),
    ]
