# Generated by Django 5.1.3 on 2024-12-09 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kazik', '0008_casino_daner_alter_casino_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casino',
            old_name='image',
            new_name='logo',
        ),
    ]
