# Generated by Django 5.1.3 on 2024-12-09 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kazik', '0009_rename_image_casino_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casino',
            old_name='daner',
            new_name='baner',
        ),
    ]
