# Generated by Django 5.1.3 on 2024-12-09 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazik', '0010_rename_daner_casino_baner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casino',
            name='baner',
        ),
        migrations.AddField(
            model_name='casino',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casino_banner', to='kazik.image'),
        ),
    ]
