# Generated by Django 5.1.3 on 2024-12-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazik', '0011_remove_casino_baner_casino_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_id',
            field=models.CharField(default='0'),
        ),
    ]
