# Generated by Django 5.1.3 on 2024-12-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazik', '0013_alter_user_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
