# Generated by Django 5.1.3 on 2024-12-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazik', '0014_casino_logo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AddField(
            model_name='casino',
            name='banner_url',
            field=models.URLField(blank=True, null=True, verbose_name='Путь к банеру'),
        ),
        migrations.AddField(
            model_name='prize',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Путь к фото'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='logo_url',
            field=models.URLField(blank=True, null=True, verbose_name='Путь к фото'),
        ),
    ]
