# Generated by Django 5.1.3 on 2024-12-09 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazik', '0016_remove_daly_bonus_prizes_daly_bonus_count_prizes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daly_bonus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daly_bonus', to='kazik.user'),
        ),
    ]
