# Generated by Django 5.1.3 on 2024-12-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazik', '0017_alter_daly_bonus_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='daly_visit',
        ),
        migrations.AlterField(
            model_name='daly_bonus',
            name='day',
            field=models.IntegerField(default=1, verbose_name='Количество ежедневных входов'),
        ),
    ]
