# Generated by Django 5.1.3 on 2024-12-09 21:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazik', '0018_remove_user_daly_visit_alter_daly_bonus_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_visit',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата последнего захода в мини апп '),
        ),
    ]
