# Generated by Django 5.1.3 on 2024-12-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazik', '0019_alter_user_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daly_bonus',
            name='count_prizes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='daly_bonus',
            name='day',
            field=models.IntegerField(default=0, verbose_name='Количество ежедневных входов'),
        ),
    ]
