# Generated by Django 5.1.3 on 2024-12-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazik', '0020_alter_daly_bonus_count_prizes_alter_daly_bonus_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='free_case',
            field=models.BooleanField(blank=True, null=True, verbose_name='Приз для Бесплатного кейса'),
        ),
        migrations.AddField(
            model_name='prize',
            name='wheel_of_fortune',
            field=models.BooleanField(blank=True, null=True, verbose_name='Приз для колеса фортуны'),
        ),
    ]
