# Generated by Django 5.1.3 on 2024-12-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazik', '0021_prize_free_case_prize_wheel_of_fortune'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='chance',
            field=models.FloatField(default=0, verbose_name='Шанс выпадения приза'),
        ),
    ]
