# Generated by Django 5.1.3 on 2024-12-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazik', '0022_prize_chance'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='url_product',
            field=models.URLField(blank=True, null=True, verbose_name='Юрл для перехода на продукт'),
        ),
    ]
