# Generated by Django 5.1.3 on 2024-12-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazik', '0023_prize_url_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер приза (если несколько ваучеров)'),
        ),
    ]
