# Generated by Django 5.1.3 on 2024-12-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazik', '0024_prize_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casino',
            name='number_of_casino',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядок (нумерация) для фильтров'),
        ),

        migrations.RenameField(
            model_name='prize',
            old_name='name',
            new_name='text', ),

        migrations.RenameField(
            model_name='prize',
            old_name='image',
            new_name='picture', ),

        migrations.RenameField(
            model_name='prize',
            old_name='image_url',
            new_name='image', ),
    ]
