# Generated by Django 5.1.3 on 2024-12-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazik', '0025_alter_casino_number_of_casino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prize',
            name='url_product',
        ),
        migrations.AddField(
            model_name='prize',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Путь к фото'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Юрл для перехода на продукт'),
        ),
    ]
