# Generated by Django 5.1.3 on 2024-12-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazik', '0026_remove_prize_url_product_prize_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='url_product',
            field=models.URLField(blank=True, null=True, verbose_name='Юрл для перехода на продукт'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='text',
            field=models.CharField(max_length=40, verbose_name='Название'),
        ),
    ]
