# Generated by Django 5.1.3 on 2024-12-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazik', '0027_prize_url_product_alter_prize_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='descriptions',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
