# Generated by Django 5.1.3 on 2024-12-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazik', '0028_prize_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prize',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='casino',
            name='descriptions',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
