# Generated by Django 5.1.3 on 2024-12-12 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazik', '0029_remove_prize_descriptions_casino_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='image_without_background_url',
            field=models.URLField(blank=True, null=True, verbose_name='Путь к фото без фона'),
        ),
        migrations.AddField(
            model_name='prize',
            name='picture_without_background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prizes_without', to='kazik.image', verbose_name='Картинка без фона'),
        ),
    ]
