# Generated by Django 5.1.3 on 2024-12-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazik', '0032_banners_delete_personal_visit_on_casino'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='numbers',
            field=models.IntegerField(default=0),
        ),
    ]
