# Generated by Django 5.1.3 on 2024-12-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazik', '0034_alter_banners_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='numbers',
            field=models.IntegerField(verbose_name='Нумерация'),
        ),
    ]
