# Generated by Django 5.1.3 on 2024-12-18 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazik', '0035_alter_banners_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prize', to='kazik.image'),
        ),
    ]
