# Generated by Django 5.1.3 on 2024-12-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazik', '0036_alter_prize_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='number_of_choice',
            field=models.IntegerField(default=0, verbose_name='Порядок нумерации призов'),
        ),
    ]
