# Generated by Django 5.1.3 on 2024-12-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazik', '0037_prize_number_of_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
