# Generated by Django 5.1.3 on 2024-12-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazik', '0038_prize_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='casino',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='casinos', to='kazik.category'),
        ),
    ]
