# Generated by Django 5.1.3 on 2024-12-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazik', '0039_category_casino_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casino',
            name='descriptions',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание'),
        ),
    ]
