# Generated by Django 5.1.3 on 2024-12-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazik', '0041_alter_prize_number_of_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daly_bonus',
            name='count_prizes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='daly_bonus',
            name='day',
            field=models.IntegerField(default=1, verbose_name='Количество ежедневных входов'),
        ),
    ]
