# Generated by Django 5.1.3 on 2024-12-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazik', '0042_alter_daly_bonus_count_prizes_alter_daly_bonus_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='set_sign',
            field=models.BooleanField(default=False, verbose_name='Уставил ли иконку на телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_get_daly_bonus',
            field=models.BooleanField(default=True, verbose_name='Можно ли получить бонус'),
        ),
    ]
